-- MySQL Script generated by MySQL Workbench
-- 06/26/17 16:08:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema auth
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema auth
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auth` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `auth` ;

-- -----------------------------------------------------
-- Table `auth`.`resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth`.`resource` (
  `id` BIGINT NOT NULL,
  `type` VARCHAR(16) NOT NULL COMMENT '权限类型[SYS,MENU,ELEMENT,OPERATION]',
  `res_key` VARCHAR(64) NOT NULL COMMENT '资源唯一标识',
  `parent_id` BIGINT NULL COMMENT '父级资源',
  `creation_date` DATETIME NOT NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `resource_u1` ON `auth`.`resource` (`res_key` ASC);


-- -----------------------------------------------------
-- Table `auth`.`operation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth`.`operation` (
  `id` BIGINT NOT NULL,
  `res_id` BIGINT NOT NULL COMMENT '资源ID',
  `name` VARCHAR(32) NOT NULL COMMENT '功能操作名',
  `uri` VARCHAR(128) NULL COMMENT '访问URI',
  `menu` INT NULL COMMENT '是否菜单[0否,1是]',
  `creation_date` DATETIME NOT NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `operation_u1` ON `auth`.`operation` (`res_id` ASC);


-- -----------------------------------------------------
-- Table `auth`.`sys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth`.`sys` (
  `id` BIGINT NOT NULL,
  `res_key` VARCHAR(64) NOT NULL COMMENT '资源唯一标识',
  `name` VARCHAR(32) NOT NULL COMMENT '系统名',
  `url` VARCHAR(64) NULL COMMENT '访问URL',
  `creation_date` DATETIME NOT NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `sys_u1` ON `auth`.`sys` (`res_key` ASC);


-- -----------------------------------------------------
-- Table `auth`.`element`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth`.`element` (
  `id` BIGINT NOT NULL,
  `res_id` BIGINT NOT NULL COMMENT '资源ID',
  `name` VARCHAR(32) NOT NULL COMMENT '元素名',
  `creation_date` DATETIME NOT NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `element_u1` ON `auth`.`element` (`res_id` ASC);


-- -----------------------------------------------------
-- Table `auth`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth`.`user` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(32) NULL COMMENT '用户显示名',
  `account` VARCHAR(32) NULL COMMENT '用户账号',
  `pwd` VARCHAR(64) NULL COMMENT '用户密码',
  `status` INT NULL COMMENT '用户状态[]',
  `creation_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auth`.`authorization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth`.`authorization` (
  `id` BIGINT NOT NULL,
  `user_id` BIGINT NULL COMMENT '用户ID',
  `group_id` BIGINT NULL COMMENT '角色组ID',
  `res_id` BIGINT NOT NULL COMMENT '资源ID',
  `creation_date` DATETIME NOT NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auth`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth`.`group` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  `status` INT NULL,
  `desc` VARCHAR(128) NULL,
  `creation_date` DATETIME NOT NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auth`.`user_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth`.`user_group` (
  `id` BIGINT NOT NULL,
  `user_id` BIGINT NULL,
  `group_id` BIGINT NULL,
  `creation_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
